name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # -------------------------------
      # Build Laravel Image
      # -------------------------------
      # - name: Build Laravel Docker Image
      #   run: docker build -t eduard2005/my-laravel-app:${{ github.sha }} ./test-app-laravel

      # - name: Push Laravel Image to Docker Hub
      #   run: |
      #     echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      #     docker push eduard2005/my-laravel-app:${{ github.sha }}

      # - name: Update development/laravel.yaml image tag
      #   run: |
      #     sed -i "s|image: eduard2005/my-laravel-app:.*|image: eduard2005/my-laravel-app:${GITHUB_SHA}|g" development/laravel.yaml

      # -------------------------------
      # Build Node API Image
      # -------------------------------
      - name: Build Node API Docker Image
        run: docker build -t eduard2005/node-api:${{ github.sha }} ./test-app-node

      - name: Push Node API Image to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push eduard2005/node-api:${{ github.sha }}

      - name: Update development/node-api.yaml image tag
        run: |
          sed -i "s|image: eduard2005/node-api:.*|image: eduard2005/node-api:${GITHUB_SHA}|g" development/node-api.yaml

      # -------------------------------
      # Commit updated YAMLs
      # -------------------------------
      - name: Commit updated YAMLs
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add development/node-api.yaml
          git commit -m "Update Docker image tags to $GITHUB_SHA" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/EduardARMENIA/cluster-k8s.git HEAD:main
